### PR TITLE
Update main.go

### PR DESCRIPTION
**Pull request by rigoford**

### CODE REVIEW

**Comment by rigoford** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To fully approve this pull request, please assign additional approvers.
We suggest the following additional approver: **rigoford**

If they are not already assigned, you can assign the PR to them by writing `/assign @rigoford` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=rigoford%2Falice).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/rigoford/alice/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by rigoford** [comment]
:star: PR built and available in a preview environment **rigoford-alice-pr-2** [here](http://alice.jx-rigoford-alice-pr-2.35.228.46.30.nip.io)

**Review by uncletravellingmart — COMMENTED** [review]
/approve

**Review by uncletravellingmart — APPROVED** [review]

**Comment by rigoford** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/rigoford/alice/pull/2#pullrequestreview-241223752" title="Approved">uncletravellingmart</a>*

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=rigoford%2Falice).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/rigoford/alice/blob/master/OWNERS)~~ [uncletravellingmart]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Pull request merged**
